---
- name: Copy Crossplane CLI binary to Kubernetes nodes
  ansible.builtin.copy:
    src: files/crossplane
    dest: /usr/local/bin/crossplane
    mode: '0755'
    remote_src: no
  become: true
  tags: [install, crossplane-cli]
  when:
    - "'kubernetes' in group_names"  # 仅针对k8s节点执行
    - ansible_os_family == "RedHat"  # 限制在RHEL/CentOS系统
  register: crossplane_cli_installed
  changed_when: crossplane_cli_installed.changed

- name: Verify CLI installation
  ansible.builtin.stat:
    path: /usr/local/bin/crossplane
  register: cli_check
  changed_when: false
  when: 
    - "'kubernetes' in group_names"
    - crossplane_cli_installed is changed

- name: Ensure Crossplane CLI is executable
  ansible.builtin.debug:
    msg: "Crossplane CLI successfully installed at /usr/local/bin/crossplane"
  when:
    - cli_check.stat is defined
    - cli_check.stat.exists
    - cli_check.stat.executable
